server:
  port: 8080
spring:
  application:
    name: nacosclient
  cloud:
    nacos:
      server-addr: ekkosblog.online:8848
      discovery:
        metadata:
          service-id: ${spring.application.name}01
#        service: 配置服务的名称,默认引用application.name
#        server-addr: 默认引用nacos.server-addr,应该在这里配置
#        cluster-name: Nacosclient 集群名称
